markdown: kramdown
permalink: /:title
url: "http://nodeschool.io/montreal"
timezone: America/Montreal

kramdown:
  input: GFM

# Use the following plug-ins
gems:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: :compressed

# Exclude these files from your production _site
exclude:
  - README.md
  - .editorconfig
  - Procfile
  - .sass-cache/
  - tasks/

mentors:
  - name: pcuci
    display: 'Paul Cuciureanu'
    twitter: pcuci
  - name: cassie
    display: 'Cassie L. Rhéaume'
    twitter: cassierheaume
  - name: andre-john
    display: 'André John Mas'
    twitter: ajmas
  - name: david
    display: 'David Rowley'
    twitter: davidrowley514
  - name: valeri
    display: 'Valeri Vicneanschi'
    twitter: vicneanschi
  - name: shawn
    display: 'Shawn Thmpson'
    twitter: plansmash
  - name: nicolas
    display: 'Nicolas Géré'
    twitter: nicolasgere
  - name: matan
    display: 'Matan Kushner'
    twitter: matchai
  - name: harris
    display: 'Harris Robin Kalash'
    twitter: LulzHRK
  - name: ziad-saab
    display: 'Ziad Saab'
    twitter: ZiadDotHTML
  - name: rsayar
    display: 'Rami Sayar'
    twitter: ramisayar
  - name: richardlitt
    display: 'Richard Littauer'
    twitter: richlitt
